version: "3.9"

services:
  flask_app:
    container_name: service-mqtt
    image: pupan/backend
    restart: always
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
      - COMPOSE_HTTP_TIMEOUT=120
volumes:
  pgdata: {}
